export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE"

export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST"
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS"
export const GET_ORDER_BY_ID_FAILURE = "GET_ORDER_BY_ID_FAILURE"

export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST'; // New action type for getting orders
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'; // New action type for successful orders retrieval
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE'; // New action type for orders retrieval failure


export const ORDER_HISTORY_REQUEST = "ORDER_HISTORY_REQUEST"
export const ORDER_HISTORY_SUCCESS = "ORDER_HISTORY_SUCCESS"
export const ORDER_HISTORY_FAILURE = "ORDER_HISTORY_FAILURE"